# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-archaeodiet-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  # nf-core: Add required software dependencies here
  - bioconda::multiqc=1.9
  - bioconda::malt=0.5.0
  - bioconda::samtools=1.10
  - bioconda::damageprofiler=1.1
  - bioconda::malt=0.5.0
  - conda-forge::pigz=2.3.4
  - bioconda::entrez-direct=13.3
  - bioconda::picard=2.23.3
  - conda-forge::ete3>=3.1.1
  - bioconda::pysam>=0.15.2
  - bioconda::entrezpy>=2.0.5
  - maxibor::pydamage>=0.3.0
